spring:
  application:
    name: discodeit
  profiles:
    active: dev  # 기본 프로파일

discodeit:
  storage:
    type: local
    local:
      root-path: uploads

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    doc-expansion: list
  api-docs:
    enabled: true
    path: /api-docs

logging:
  level:
    root: INFO

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - loggers
          - metrics
  info:
    env:
      enabled: true

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 3.4.0
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    storage:
      type: ${discodeit.storage.type}
      path: ${discodeit.storage.local.root-path}
    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size:10MB}
      max-request-size: ${spring.servlet.multipart.max-request-size:10MB}