name: CI - Test and CodeCov

on:
  # 누군가 main이나 release에 코드를 직접 push하거나 merge했을 때 실행
  push:
    branches:
      - main
      - release
  # 누군가 main으로 PR을 날렸을 때 미리 검사하기 위해 실행
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests with Gradle
        run: ./gradlew test jacocoTestReport

      # 생성된 커버리지 리포트를 CodeCov로 업로드
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/jacoco/test/jacocoTestReport.xml